  
language: java

cache:
  directories:
    - $HOME/.m2

matrix:
  include:

    - env: DEPLOY='linux'
      jdk: openjdk11

    - env: DEPLOY='linux-15'
      jdk: openjdk15

    - env: DEPLOY='linux-early-access'
      jdk: openjdk-ea

    - env: DEPLOY='macos'
      os: osx
      jdk: openjdk11
      
    - env: DEPLOY='macos-15'
      os: osx
      jdk: openjdk15

    - env: DEPLOY='macos-early-access'
      os: osx
      jdk: openjdk-ea

    - env: DEPLOY='linux-early-access-loom' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-loom"

    - env: DEPLOY='linux-early-access-lworld' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-lworld"

    - env: DEPLOY='linux-early-access-sealed' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-sealed"

    - env: DEPLOY='linux-early-access-pattern' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-pattern"

    - env: DEPLOY='linux-early-access-vector' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-vector"
      
  ##  - env: DEPLOY='macos-early-access-loom' TAG="untagged-f3dc9f90c6e0a06c83c1" NAME="jdk-15-loom"
  ##    os: osx

  ##  - env: DEPLOY='macos-early-access-lworld' TAG="untagged-f3dc9f90c6e0a06c83c1" NAME="jdk-15-lworld"
  ##    os: osx

    - env: DEPLOY='macos-early-access-sealed' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-sealed"
      os: osx

    - env: DEPLOY='macos-early-access-pattern' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-pattern"
      os: osx

    - env: DEPLOY='macos-early-access-vector' TAG="untagged-a6acf5c962e51cb48b3c" NAME="jdk-16-vector"
      os: osx

#  allow_failures:
#     - env: NAME="jdk-13-record"

before_install:
  - if [[ -n $TAG ]]; then wget https://github.com/forax/java-next/releases/download/$TAG/$NAME-$TRAVIS_OS_NAME.tar.gz   ; fi
  - if [[ -n $TAG ]]; then tar zxvf $NAME-$TRAVIS_OS_NAME.tar.gz   ; fi
  - if [[ -n $TAG ]]; then export JAVA_HOME=$NAME   ; fi
  - if [[ -n $TAG ]]; then export PATH=$JAVA_HOME/bin:$PATH   ; fi
  - if [[ ! -n $JAVA_HOME ]]; then export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home"  ; fi
  
install:
  - echo $JAVA_HOME
  - java --version

script:
  - export JAVA_TOOL_OPTIONS="-XX:+UnlockDiagnosticVMOptions -XX:DisableIntrinsic=_bigIntegerLeftShiftWorker,_bigIntegerRightShiftWorker -XX:CompileCommand=dontinline,java.math.BigInteger::shiftLeft -XX:CompileCommand=dontinline,java.math.BigInteger::shiftRight"
  - chmod u+x ./build.sh
  - ./build.sh
  - ./target/pro/bin/pro version
  - ./target/pro/bin/pro build test.pro

before_deploy:
  - cd target
  - jar cvfM ../pro-$DEPLOY.zip pro
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: "LK+rfK0Ryhscy7QBYTTTqUEfwgHg8y/7rB4VJ+5i+w5XbkJNLZ031Rg3sfo71v0LybnfdjXc9myirqbEc4E4mUF0StXQTDzidJuvbaNkvxq9axJH3vhs8tBaI6cDisANSpWg5BpDEEffyW6+q2p2fiy2mKH58dHOryOq0sH+w1HtDUiJRvV5G68mcNYL7B60yuog0XFIwJMDq+yPQNwf6XCJ2Nlgk9h1liZY25Y4bSlXvBGN/SLQbVk5h4RVFXognyPFb8OOlpv7N1093POL918MveHJYjrzZAuLiZr3VhAD/HDNq66ytfZXE6FpS1hOitw0KryM/xMVDogs5ezWJLeRZ+HP3mESh+YeIE/6CqxMx4eFpQNp34EWtiizDa9hP97WcE7GsOTHndQ2oYC2fdMAm5WJUwgwdvhP7N/8p/BJgjCa9sreQa6xYYdPGK/JQAWauSY80YvFBx87wkiMonVcLph/8253zKjZ8APwQNTTd0k+Xx9TaU3VVDMnpBeUfYvUbzfNl+RUllMbxVvUe6sZjkAHTW8DpIbt8PyDFH44cSekcnTsDlSFhag85koBlsi0KmG1mvjAkDCzrB8VhJeX9krLzsruZSeL7b6K2pASzDsy+dalePuXWatW/PsFBorvlRy0e0K8zh+rbVUIFJLp+HCCSJ3V7JRLA45C/+c="
  file: pro-$DEPLOY.zip
  skip_cleanup: true
  prerelease: true
  on:
    tags: true
    condition: $DEPLOY != 'false'
